// Run with PGLITE_MODULE pointing to @electric-sql/pglite's dist/index.js.
import {readFile} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db=new PGlite();let checks=0;
const W=randomUUID(),U=randomUUID(),OTHER=randomUUID();
const md5=s=>{const h=createHash('md5').update(s).digest('hex');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`};
await db.exec(`create schema auth;create role anon;create role authenticated;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table public.profiles(id uuid primary key);
create table public.workspaces(id uuid primary key,timezone text default 'UTC',rollover_hour smallint default 6);
create table public.workspace_members(workspace_id uuid,user_id uuid);
create function public.is_workspace_member(w uuid) returns boolean language sql as $$select exists(select 1 from public.workspace_members where workspace_id=w and user_id=auth.uid())$$;
create table public.tasks(id uuid primary key,workspace_id uuid not null,owner_user_id uuid not null,created_by uuid not null,title text,description text,original_date date not null,priority text default 'normal',completed_at timestamptz,deleted_at timestamptz,updated_at timestamptz default now());
grant usage on schema public,auth to authenticated;grant select,insert,update on all tables in schema public to authenticated;
insert into public.profiles values('${U}'),('${OTHER}');insert into public.workspaces(id) values('${W}');insert into public.workspace_members values('${W}','${U}'),('${W}','${OTHER}');`);
await db.exec(await readFile(new URL('../migrations/20260921205335_wardrobe_native_v1.sql',import.meta.url),'utf8'));
await db.exec(`create trigger test_task_schedule before insert on public.tasks for each row execute function public.validate_new_task_schedule();set role authenticated;select set_config('request.jwt.claim.sub','${U}',false);`);
const doc={id:md5(`wardrobe:${W}:${U}`),workspace_id:W,owner_user_id:U,change_id:randomUUID(),state:{categories:[{id:'tshirts',name:'T-shirts',kind:'top'}],items:[{id:randomUUID(),name:'White T-shirt',category:'tshirts',color:'#FFFFFF',shape:'jacket',sleeve:'short',hood:'yes',use:'both',pieces:[{id:randomUUID(),status:'laundry',laundry_token:randomUUID()},{id:randomUUID(),status:'laundry',laundry_token:randomUUID()}]}],outfits:[],threshold:2,sequence:1,batches:[]}};
const makeBatch=(d,sequence)=>({sequence,task_id:md5(`${d.id}:laundry:${sequence}`),date:'2026-01-01',completed_at:null,entries:d.state.items[0].pieces.map(p=>({piece_id:p.id,token:p.laundry_token}))});
doc.state.batches.push(makeBatch(doc,1));
const sync=async(d,version)=>(await db.query('select * from public.sync_wardrobe($1::jsonb,$2)',[JSON.stringify(d),version])).rows[0];
const count=async()=>Number((await db.query('select count(*) as n from public.tasks')).rows[0].n);
const check=()=>checks++;
let server=await sync(doc,0);assert.equal(await count(),1);assert.equal(server.revision,1);check();
assert.equal(server.state.items[0].shape,'jacket');assert.equal(server.state.items[0].sleeve,'short');assert.equal(server.state.items[0].hood,'yes');check();
assert.equal((await sync(doc,0)).revision,1);assert.equal(await count(),1);check();
await assert.rejects(sync({...doc,change_id:randomUUID()},0),e=>e.code==='PT409');check();
await assert.rejects(sync({...doc,change_id:randomUUID()},null),e=>e.code==='22023');check();
assert.equal((await db.query('select original_date::text as date from public.tasks')).rows[0].date,'2026-01-01');check();
await db.exec(`select set_config('request.jwt.claim.sub','${OTHER}',false)`);
assert.equal((await db.query('select * from public.wardrobes')).rows.length,0);await assert.rejects(sync(doc,1),e=>e.code==='42501');check();
await db.exec(`select set_config('request.jwt.claim.sub','${U}',false)`);
const task=doc.state.batches[0].task_id;
await assert.rejects(db.query('update public.tasks set owner_user_id=$1 where id=$2',[OTHER,task]));check();
await db.query('update public.tasks set completed_at=now() where id=$1',[task]);
server=(await db.query('select * from public.wardrobes')).rows[0];assert.ok(server.state.items[0].pieces.every(p=>p.status==='available'));assert.ok(server.state.batches[0].completed_at);check();
await db.query('update public.tasks set completed_at=null where id=$1',[task]);
let next=structuredClone(server);next.change_id=randomUUID();next.state.sequence=2;next.state.items[0].pieces.forEach(p=>{p.status='laundry';p.laundry_token=randomUUID()});next.state.batches.push(makeBatch(next,2));
server=await sync(next,server.revision);assert.equal(await count(),2);check();
await db.query('update public.tasks set completed_at=now() where id=$1',[task]);
server=(await db.query('select * from public.wardrobes')).rows[0];assert.ok(server.state.items[0].pieces.every(p=>p.status==='laundry'));check();
let bad=structuredClone(server);bad.change_id=randomUUID();bad.state.items[0].pieces.push(bad.state.items[0].pieces[0]);await assert.rejects(sync(bad,server.revision));assert.equal(await count(),2);check();
bad=structuredClone(server);bad.change_id=randomUUID();bad.state.batches[0].completed_at=null;await assert.rejects(sync(bad,server.revision));check();
next=structuredClone(server);next.change_id=randomUUID();next.state.items[0].pieces.forEach(p=>p.status='available');next.state.batches[1].completed_at=new Date().toISOString();server=await sync(next,server.revision);
assert.ok((await db.query('select completed_at from public.tasks where id=$1',[next.state.batches[1].task_id])).rows[0].completed_at);check();
const result=await db.query('select relrowsecurity from pg_class where oid=\'public.wardrobes\'::regclass');assert.equal(result.rows[0].relrowsecurity,true);check();
console.log(`${checks} wardrobe database checks passed: atomic task creation, RLS, version conflicts, retries, offline dates, completion, reopening, immutable history and validation.`);
await db.close();
